### PR TITLE
Create nextcloud-caldav.service.in

### PR DESCRIPTION
**Pull request by ernesst**
Dear, 
The Nextcloud online account plugin landed in the devel, now we need to enable service to use it.

### CODE REVIEW

**Comment by Flohack74** [comment]
I merged this for now, but we need to check whats going on again here with the build, I see red marks from Jenkins...

**Comment by mardy** [comment]
@Flohack74 Please let's not merge stuff this quickly, I didn't even have the time to look at it... :-)

Thanks @ernesst , the files are correct, but you also need to modify the `CMakeFile.txt` in each directory in order to install them, and also modify the .install files in the `debian` directory so that the new two files end up in the .deb packages.

**Comment by mardy** [comment]
The build fails because the package is being built for xenial, and probably we need some more changes to build it there correctly.
@mariogrip I see that the Jenkinsfile requires the xenial-arm node; but I guess that's not the reason why xenial is selected, or is it? Can you help us understand why this is being built for xenial?

**Comment by mariogrip** [comment]
@mardy Seems to have a old jenkinsfile please update https://github.com/ubports/build-tools/blob/master/Jenkinsfile

**Pull request merged**
