### PR TITLE
update CMakeFile and Debian for Nextcloud account

### PR DESCRIPTION
**Pull request by ernesst**
According to the request from the pull #2 
see enclosed the missing pieces.

### CODE REVIEW

**Comment by mardy** [comment]
Please don't merge this before the CI completes successfully. And then, use "Squash and merge" to merge it.

**Comment by mariogrip** [comment]
@mardy This pr seems to use the old jeninsfile, I might add a "redirect" from "build-and-provide-package" to the new "build-binary.sh" script, since that is what has changed in the jenkinsfile.

**Comment by mariogrip** [comment]
@ernesst could you try merge https://github.com/ubports/sync-monitor/commit/013b751030099516b6058aa1236b9d493831578c into your pr?

**Review by mardy — CHANGES_REQUESTED** [review]
Please rebase your branch on top of the latest `vivid` branch, so that CI should succeed.

**Pull request merged**
